### ISSUE TITLE
pyfsxfs_test_volume.py is missing in source package

### ISSUE THREAD

**Issue by vwegert** [libyal/libfsxfs#9]
Similar to [this](https://github.com/libyal/libfwnt/issues/12) and [this](https://github.com/libyal/libwrc/issues/1) issue: The file `tests/pyfsxfs_test_volume.py` is present in the main Git repository, but missing in the released source packages. This causes the test to fail when run with `make check`. Manually adding the file from the master repository fixes the issue locally.

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libfsxfs/commit/e251c838ab70485a35cdf30344526cd9d38332b2
